name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: PHP Code Style (phpcs)
      # You may pin to the exact commit or the version.
      # uses: chindit/actions-phpcs@ccda708ed581ebe13a66497cc47c07b8346af3b3
      uses: chindit/actions-phpcs@1.0.1
      with:
        # Folder to check code style
        dir: ./
        
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
